In [1]:
import numpy as np

# 1-D arrays


In [4]:
# vectorization
a = np.zeros(4)
b = np.arange(4.)
c = np.random.rand(4)
d = np.array([5,4,3,2])
print(a)
print(b)
print(c)
print(d)
print(a.shape)
print(d.shape)

[0. 0. 0. 0.]
[0. 1. 2. 3.]
[0.15683462 0.65995392 0.08746069 0.11994902]
[5 4 3 2]
(4,)
(4,)


In [ ]:
# indexing
a = np.arange(10)
print(a)
print(f"a[-1] = {a[-1]}")

[0 1 2 3 4 5 6 7 8 9]
a[-1] = 9


In [6]:
# slicing
a = np.arange(10)
print(f"a         = {a}")
# access 3 elements separated by two 
c = a[2:7:2];     print("a[2:7:2] = ", c)

a         = [0 1 2 3 4 5 6 7 8 9]
a[2:7:2] =  [2 4 6]


In [7]:
# Single vector operations
a = np.array([1,2,3,4])
print(f"a             : {a}")
# negate elements of a
b = -a 
print(f"b = -a        : {b}")

# sum all elements of a, returns a scalar
b = np.sum(a) 
print(f"b = np.sum(a) : {b}")

b = np.mean(a)
print(f"b = np.mean(a): {b}")

b = a**2
print(f"b = a**2      : {b}")

a             : [1 2 3 4]
b = -a        : [-1 -2 -3 -4]
b = np.sum(a) : 10
b = np.mean(a): 2.5
b = a**2      : [ 1  4  9 16]


In [9]:
# Scalar Vector operations
a = np.array([1, 2, 3, 4])

# multiply a by a scalar
b = 5 * a 
print(f"b = 5 * a : {b}")

b = 5 * a : [ 5 10 15 20]


In [ ]:
# vectors operation 

# adding
a = np.array([ 1, 2, 3, 4])
b = np.array([-1,-2, 3, 4])
print(f"Binary operators work element wise: {a + b}")

# dot product
a = np.array([1, 2, 3, 4])
b = np.array([-1, 4, 3, 2])
c = np.dot(a, b)
print(f"NumPy 1-D np.dot(a, b) = {c}, np.dot(a, b).shape = {c.shape} ") 

Binary operators work element wise: [0 0 6 8]
NumPy 1-D np.dot(a, b) = 24, np.dot(a, b).shape = () 


# multi-D matrices

## 判断维度

1.肉眼判断：直接看括号后紧接着的[数量就行

2.程序判断：

    (1) print(a.ndim) 直接给出rank值

    (2) print(b.shape) 给出具体的数据结构,元组内有几个值,就是几维
        - 1维：(4,) 4个元素
        - 2维：(2,3) 2行 3列
        - 3维：(4,3,2) 4 层（4个2维） 每层（每个2维）中3行 每行中2列
        - 4维：(2,3,3,5) 2个3维 每个3维中3个2维 每个2维中3行5列

In [19]:
# create 2-D matrices

a = np.zeros((1, 5))     # 1行5列                                  
print(f"a shape = {a.shape}, a = {a}")

b = np.zeros((3, 1)) # 3行一列
print(f" b shape = {b.shape}, np.array: b = {b}")

c = np.zeros((2, 2))        #2行2列                                                           
print(f"c shape = {c.shape}, c = {c}") 

# create 3-D matrices
d = np.zeros((2, 2, 3))     #2层，每层2行3列                                                              
print(f"d shape = {d.shape}, d = {d}") 

a shape = (1, 5), a = [[0. 0. 0. 0. 0.]]
 b shape = (3, 1), np.array: b = [[0.]
 [0.]
 [0.]]
c shape = (2, 2), c = [[0. 0.]
 [0. 0.]]
d shape = (2, 2, 3), d = [[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]]


In [21]:
# 该结构是3行1列的2维矩阵
a = np.array([[5], [4], [3]]);   print(f" a shape = {a.shape}, np.array: a = {a}")

 a shape = (3, 1), np.array: a = [[5]
 [4]
 [3]]


In [25]:
#vector indexing operations on matrices

#reshape is a convenient way to create matrices
a = np.arange(6).reshape(-1, 2)   # reshape中-1的含义是：规定列数是2后，行数自动计算

print(f"a.shape: {a.shape}, \na= {a}")

#access a row
print(f"a[2]   = {a[2]}")

#access an element
print(f"a[2,0] = {a[2, 0]}")

a.shape: (3, 2), 
a= [[0 1]
 [2 3]
 [4 5]]
a[2]   = [4 5]
a[2,0] = 4


In [28]:
#vector 2-D slicing operations
a = np.arange(20).reshape(-1, 10)
print(f"a = \n{a}")

#access 5 consecutive elements (start:stop:step)
print(a[0, 2:7:1])

#access 5 consecutive elements (start:stop:step) in two rows
print(a[:, 2:7:1])

# access all elements
print(a[:,:])

# access all elements in one row (very common usage)
print(a[1,:])
# same as
print(a[1])

a = 
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]
[2 3 4 5 6]
[[ 2  3  4  5  6]
 [12 13 14 15 16]]
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]
[10 11 12 13 14 15 16 17 18 19]
[10 11 12 13 14 15 16 17 18 19]
