In [2]:
import numpy as np

# 基操

#### numpy.arange

In [ ]:
# numpy.arange(start, stop, step, dtype)
# dtype: https://www.runoob.com/numpy/numpy-dtype.html
x = np.arange(0,100,2.5, dtype = np.int16) 
print (x)
print (x.size) # x.shape元组中所有数字相乘等于size大小
# 重构2维数组
x_2D = x.reshape(5,8)
print (x_2D)
# 重构3维数组
x_3D = x.reshape(4,2,5)
print (x_3D)

#### numpy.zeros/ones/full

In [3]:
# numpy.zeros(shape, dtype = float, order = 'C')
# order：'C' 用于 C 的行数组,或者 'F' 用于 FORTRAN 的列数组
x = np.zeros(10,dtype = np.int16) 
print (x)

# numpy.ones(shape, dtype = None, order = 'C')
y = np.ones((2,3),dtype = np.int16) 
print (y)

z = np.full((2,3,4),9,dtype = np.int16) 
print (z)

[0 0 0 0 0 0 0 0 0 0]
[[1 1 1]
 [1 1 1]]
[[[9 9 9 9]
  [9 9 9 9]
  [9 9 9 9]]

 [[9 9 9 9]
  [9 9 9 9]
  [9 9 9 9]]]


#### numpy.random

In [ ]:
# [0,1)
x = np.random.random((2,3,4)) 
print (x)

# 生成标准正态分布（均值为 0,标准差为 1）
y = np.random.randn(2,3,4) # 注意这里括号个数
print (y)

# 整数
z = np.random.randint(2,34,size=(2,3,4)) 
print (z)

#### np.linspace/np.logspace

指定范围内返回“等间距”数组

In [3]:
# 在一个区间内返回等间距数组
arr1 = np.linspace(1, 101, 5)
print(arr1.shape)
print(arr1)

arr2 = np.linspace(1, 101, 5, endpoint=False)
print(arr2.shape)
print(arr2)

# 起始对数值和结束对数值实际上是在定义数组中值的对数范围
# 10^0=1, 10^2=100
arr3 = np.logspace(0, 2, 5, endpoint=True)
print(arr3.shape)
print(arr3)

(5,)
[  1.  26.  51.  76. 101.]
(5,)
[ 1. 21. 41. 61. 81.]
(5,)
[  1.           3.16227766  10.          31.6227766  100.        ]


#### 索引 index

In [84]:
row_Students=[1,2,3,4,5,6]
row_Math =[66,34,88,96,57,70]
row_English=[58,22,100,49,65,34]
row_Sport=[99,84,48,38,25,56]

students = np.array([row_Students,row_Math,row_English,row_Sport]) 

# print(students)
# print(students.shape)

# # 列查找（先查行,再查列）
# print(students[1:,3]) # 查找学号=4的学生所有成绩
# print(students[:,::2]) # 查找学号=1,3,5的学生所有成绩+学号

# 值查找
mark = (students >= 60) & (students < 90)
print(np.where(mark,students,np.nan)) # where(筛选条件,从哪里筛选,不满足时填的值)
print(np.argwhere(mark)) # 查看符合条件值的数据位置


# # 不好的做法
# print(mark) # 保留数据结构,但显示bool
# print(students[mark]) # 不保留数据结构,直接出筛选出的值


[[nan nan nan nan nan nan]
 [66. nan 88. nan nan 70.]
 [nan nan nan nan 65. nan]
 [nan 84. nan nan nan nan]]
[[1 0]
 [1 2]
 [1 5]
 [2 4]
 [3 1]]


#### 连接、插入、去重等操作

更多操作详见：https://www.runoob.com/numpy/numpy-array-manipulation.html#numpy_oparr4

In [93]:
# numpy.concatenate((a1, a2, ...), axis)
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
print (np.concatenate((a,b))) # 沿轴 0 连接两个数组
print (np.concatenate((a,b),axis = 1)) # 沿轴 1 连接两个数组

# numpy.insert(被插入数组,再这个数字的索引前插入,插入的值, axis如果未提供，则输入数组会被展开)
c = [11,12]
print(np.insert(a,1,c))
print(np.insert(a,1,c,axis = 0))
print(np.insert(a,1,c,axis = 1))

# 去重
x = np.array([1,2,1,0]) 
x2 = np.unique(x)
print(x2)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]
[ 1 11 12  2  3  4]
[[ 1  2]
 [11 12]
 [ 3  4]]
[[ 1 11  2]
 [ 3 12  4]]


# broadcast

In [1]:
a = np.array([1,2,3,4]) 
b = np.array([[10,20,30,40],[1,2,3,4]]) 
c = a * b 
print (c)

NameError: name 'np' is not defined

In [83]:
x = np.eye(5) # 单位矩阵
print(x)

y = x + np.array([0.1,0.2,0.3,0.4,0.5])
print(y) # 列相加

z = x + np.array([[0.1],[0.2],[0.3],[0.4],[0.5]]) 
print(z) # 行相加

print(y.sum()) # 数组里所有元素相加

 # axis = 0:从上至下；axis = 1:从左至下右；先从上至下,后从左至右（先纵轴,后横轴）
print(y.max(axis =0)) # 找每列最大值
print(y.min(axis =1)) # 找每行最小值

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[[1.1 0.2 0.3 0.4 0.5]
 [0.1 1.2 0.3 0.4 0.5]
 [0.1 0.2 1.3 0.4 0.5]
 [0.1 0.2 0.3 1.4 0.5]
 [0.1 0.2 0.3 0.4 1.5]]
[[1.1 0.1 0.1 0.1 0.1]
 [0.2 1.2 0.2 0.2 0.2]
 [0.3 0.3 1.3 0.3 0.3]
 [0.4 0.4 0.4 1.4 0.4]
 [0.5 0.5 0.5 0.5 1.5]]
12.5
[1.1 1.2 1.3 1.4 1.5]
[0.2 0.1 0.1 0.1 0.1]


# dimension

## 判断维度

1.肉眼判断：直接看括号后紧接着的[数量就行

2.程序判断：

    (1) print(a.ndim) 直接给出rank值

    (2) print(b.shape) 给出具体的数据结构,元组内有几个值,就是几维
        - 1维：(4,) 4个元素
        - 2维：(2,3) 2行 3列
        - 3维：(4,3,2) 4 层（4个2维） 每层（每个2维）中3行 每行中4列
        - 4维：(2,3,3,5) 2个3维 每个3维中3个2维 每个2维中3行5列


### 一维数组

In [ ]:
# 一维数组
numpy_array1 = np.array([1,2,3,4])
numpy_array2 = np.array([10,20,30,40])
a = numpy_array1+numpy_array2
print(a)
print(a.ndim) # 数数组的维度
print(a.shape) # 展示数组形状, 一维就展示为：（元素个数,）

a2 = np.array([[1, 2, 3, 4]])
print(a2.shape)  # 输出: (1, 4)
# 元组内有两个值的就说明他是二维数组了,一行四列

### 二维数组

In [ ]:
# 二维数组
b = np.array([[1, 2, 3], [3, 4, 5]])
print(b)
print(b.ndim) # 数数组的维度
print(b.shape) # 展示数组形状, 展示为元组：（行,列）

### 三维数组

In [ ]:
# 三维数组
c = np.array(
    [
        [[1, 2], [3, 4], [100, 200]],  # 第一层
        [[5, 6], [7, 8], [3, 4]],  # 第二层
        [[9, 10], [11, 12], [3, 4]],  # 第三层
        [[9, 10], [11, 12], [3, 4]]  # 第四层
    ]
)
print(c)
print(c.ndim) # 数数组的维度
print(c.shape) # 展示数组形状, 展示为元组：（层,每层中的行,每行中的列）
# 第一维度是层（或深度）,这里有 4 层
# 第二维度是每层中的行数,这里每层有 3 行
# 第三维度是每行中的列数,这里每行有 2 列

print(c.max(axis=0)) # 纵向的将每个位置上的数值都进行比对,最后组合起来输出结果
print(c.max(axis=1)) # 在每个层里,纵向比较每列的最大值,最后组合起来输出结果
print(c.max(axis=2)) # 在每个层里,横向比较每行的最大值,最后组合起来输出结果

### 四维数组

In [ ]:
# 四维数组
four_d_array = np.array([
    [
        [[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15]],
        [[16, 17, 18, 19, 20], [21, 22, 23, 24, 25], [26, 27, 28, 29, 30]],
        [[31, 32, 33, 34, 35], [36, 37, 38, 39, 40], [41, 42, 43, 44, 45]]
    ],
    [
        [[46, 47, 48, 49, 50], [51, 52, 53, 54, 55], [56, 57, 58, 59, 60]],
        [[61, 62, 63, 64, 65], [66, 67, 68, 69, 70], [71, 72, 73, 74, 75]],
        [[76, 77, 78, 79, 80], [81, 82, 83, 84, 85], [86, 87, 88, 89, 90]]
    ]
])
print(four_d_array.ndim)  # 输出: (2, 3, 3, 5)
print(four_d_array.shape)  # 输出: (2, 3, 3, 5)
print (four_d_array.size)  # 90 = 2*3*3*5

# 拷贝

ndarray.copy() 函数创建一个副本。

对副本数据进行修改，不会影响到原始数据，它们物理内存不在同一位置

https://www.runoob.com/numpy/numpy-copies-and-views.html

In [85]:
a = np.array([[10,10],  [2,3],  [4,5]])  
print (a)

b = a.copy()  
print (b)

[[10 10]
 [ 2  3]
 [ 4  5]]
[[10 10]
 [ 2  3]
 [ 4  5]]
